name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - Verificar estructura
        run: |
          echo "=== Verificando estructura del proyecto ==="
          pwd
          ls -la
          echo ""
          echo "=== Buscando pom.xml ==="
          find . -name "pom.xml" -type f
          echo ""
          echo "=== Verificando si hay archivos de test ==="
          find . -path "*/src/test/java/*.java" -type f | head -5

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('user-service/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests
        working-directory: user-service
        run: |
          echo "=== Ejecutando tests ==="
          mvn clean test -Dspring.profiles.active=test
          echo ""
          echo "=== Verificando si se generaron reportes ==="
          if [ -d "target/surefire-reports" ]; then
            echo "✅ Reportes de test generados:"
            ls -la target/surefire-reports/
          else
            echo "⚠️  No se generaron reportes de test (no hay tests o fallaron)"
          fi

      - name: Build with Maven
        working-directory: user-service
        run: mvn clean package -DskipTests

      - name: Check test results exist
        id: check-tests
        run: |
          if [ -d "user-service/target/surefire-reports" ] && [ "$(ls -A user-service/target/surefire-reports/)" ]; then
            echo "test_reports_exist=true" >> $GITHUB_OUTPUT
            echo "✅ Test reports found"
          else
            echo "test_reports_exist=false" >> $GITHUB_OUTPUT
            echo "⚠️  No test reports to upload"
          fi

      - name: Upload test results
        if: always() && steps.check-tests.outputs.test_reports_exist == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: user-service/target/surefire-reports/
          retention-days: 7

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: user-service-jar
          path: user-service/target/*.jar
          retention-days: 7

      # Paso adicional para mostrar resumen
      - name: Build Summary
        if: always()
        run: |
          echo "=== RESUMEN DEL BUILD ==="
          if [ -f "user-service/target/*.jar" ]; then
            echo "✅ JAR generado correctamente"
            ls -la user-service/target/*.jar 2>/dev/null || echo "JAR no encontrado"
          fi
          
          if [ -d "user-service/target/surefire-reports" ]; then
            TEST_COUNT=$(find user-service/target/surefire-reports -name "TEST-*.xml" | wc -l)
            echo "✅ Tests ejecutados: $TEST_COUNT archivos de reporte"
          else
            echo "⚠️  Sin reportes de test - verifica que tengas tests en src/test/java/"
          fi
